development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:cd172697e3c6cda452c39da90fd0873a@soldierfish.redistogo.com:10090/
  channel_prefix: backend-driver-timer_production
